### ISSUE TITLE
Firstname, Middlename and Lastname regex not supporting myanmar script unicode strings

### ISSUE THREAD

**Issue by bushjames** [mojaloop/account-lookup-service#420]
The regex used for validating Firstname, Middlename and Lastname of parties is failing to match myanmar script unicode strings.

The regex specified e.g. here: https://github.com/mojaloop/account-lookup-service/blob/master/src/interface/api-swagger.yaml#L1233

fails to match strings such as "ကောင်းထက်စံ"

Analysis e.g. here: https://www.fontspace.com/unicode/analyzer#e=4YCA4YCx4YCs4YCE4YC64YC44YCR4YCA4YC64YCF4YC2

...shows this string to consist of valid unicode points in the "myanmar" script. I believe this, and similar strings should be permitted as name elements within party objects in API elements.

**Comment by elnyry-sam-k** [comment]
moved here: https://github.com/mojaloop/project/issues/2358
