### ISSUE TITLE
account-lookup-mysql fails to start

### ISSUE THREAD

**Issue by dirkslab** [mojaloop/account-lookup-service#431]
Deployed directly from remote repo. Using AKS - tested against multiple AKS versions and setups. Last test Kubernetes version tried 1.19.11

Failed to pull image "busybox:1.25.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/busybox:1.25.0": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:8ac8bfaff55af948c796026ee867448c5b5b5d9dd3549f4006d9759b25d4a893: failed to get reader from content store: content digest sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f: not found

**Comment by mdebarros** [comment]
> Deployed directly from remote repo. Using AKS - tested against multiple AKS versions and setups. Last test Kubernetes version tried 1.19.11
> 
> Failed to pull image "busybox:1.25.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/busybox:1.25.0": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:8ac8bfaff55af948c796026ee867448c5b5b5d9dd3549f4006d9759b25d4a893: failed to get reader from content store: content digest sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f: not found

Hey @dirkslab, 

Thanks for logging the issue.

Can you provide more information on how you are deploying this?

I.e. are you deploying Mojaloop using Helm, and if so what version, etc.

In general, more specific details (i.e. application version, etc) would be useful here.

Another idea would be to jump on Slack, and ask for help in the `#help-mojaloop` channel, you can join Slack using the following link: https://mojaloop-slack.herokuapp.com/

**Comment by dirkslab** [comment]
@mdebarros thanks for the response

AKS tested deployment using arm and from the portal. Tried multiple Kubernetes versions and configs.

Chart account-lookup-service  deployed using helm

helm --namespace mojaloop install moja --repo=http://mojaloop.io/helm/repo account-lookup-service --create-namespace

Please let me know if sufficient or what additional info I can supply.

**Comment by dirkslab** [comment]
@mdebarros to clarify arm > azure resource manager template

**Comment by lewisdaly** [comment]
I remember @tdaly61 had issues with the busybox image in the past - I can't remember the exact details

**Comment by ScratZa** [comment]
I Suspect this is related to mojaloop/project#2447.

**Comment by lewisdaly** [comment]
Hi @dirkslab - the best approach for now is to disable mysql in the `values.yaml` file wherever you see the following:
```
mysql:
    enabled: false
```

From there, you can deploy your own mysql dbs and update the `db_host`, `db_user` and `db_password` fields where applicable

**Comment by lewisdaly** [comment]
https://github.com/mojaloop/ml-oss-sandbox/blob/master/config/switch/base/ss_mysql.yaml is an example of byo MySQL for the account-lookup-service and central-ledger, 

and https://github.com/mojaloop/ml-oss-sandbox/blob/master/config/switch/core/values.yaml is an example of where we update those values so that the central-ledger and account-lookup-service refer to those databases

**Comment by tdaly61** [comment]
hi @dirkslab , so yeah I have seen this and I believe it is an issue between containerd and the particular busybox image used by the percona chart.  You can definitely do as @lewisdaly suggests but what might be easier is to change the requirements.yaml for accounts-lookup-service to use plain old mysql as a starter i.e. with innodb engine instead of percona.

**Comment by murduk** [comment]
@lewisdaly thank you very much for the ss_mysql.yaml. One quick correction would be to update the image with 5.7. 5.6 is not working with the init container script. Also for the 5.7 this should be added in order to initialize mysql:

      containers:
      - image: mysql:5.7.37
        args:
        - "--ignore-db-dir=lost+found"

**Comment by elnyry-sam-k** [comment]
hi @dirkslab , as this is now 2years old without an update, I'm going to close this.

Please re-open if there's any issue with latest releases or a more relevant update. Thank you!
